version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ras:2.0
    ports:
      - "80:5000"
    restart: always
    networks:
      - rasnet

networks:
  rasnet:
    driver: bridge