apiVersion: apps/v1
kind: Deployment
metadata:
  name: ras-webapp
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ras
  template:
    metadata:
      labels:
        app: ras
    spec:
      containers:
      - name: ras
        image: ras:2.0
        ports:
        - containerPort: 5000